"use client";

import { useState } from "react";
import { ArrowUpRight, Check, LoaderCircle } from "lucide-react";

type Interest = "website" | "video" | "marketing" | "other";
type Fields = { name: string; phone: string; instagram: string; linkedin: string; email: string; interests: Interest[]; otherDetails: string; website: string };
const initial: Fields = { name: "", phone: "", instagram: "", linkedin: "", email: "", interests: [], otherDetails: "", website: "" };

export function LeadForm() {
  const [fields, setFields] = useState(initial); const [errors, setErrors] = useState<Partial<Record<keyof Fields, string>>>({}); const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle"); const [message, setMessage] = useState("");
  function update(key: keyof Fields, value: string | Interest[]) { setFields((current) => ({ ...current, [key]: value })); if (errors[key]) setErrors((current) => ({ ...current, [key]: undefined })); }
  function toggleInterest(interest: Interest) { const next: Interest[] = fields.interests.includes(interest) ? fields.interests.filter((item) => item !== interest) : [...fields.interests, interest]; update("interests", next); }
  function validate() { const next: typeof errors = {}; if (fields.name.trim().length < 2) next.name = "Please enter your full name."; if (!/^\+?[0-9 ()-]{7,20}$/.test(fields.phone)) next.phone = "Enter a valid phone number."; if (fields.instagram && !/^@?[a-zA-Z0-9._]{2,30}$/.test(fields.instagram)) next.instagram = "Enter a valid username."; if (fields.linkedin && (!/^https?:\/\//.test(fields.linkedin) || !fields.linkedin.includes("linkedin.com/"))) next.linkedin = "Enter a valid LinkedIn URL."; if (!/^\S+@\S+\.\S+$/.test(fields.email)) next.email = "Enter a valid email address."; setErrors(next); return Object.keys(next).length === 0; }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!validate() || status === "loading") return; setStatus("loading"); try { const submittedInterests = fields.interests.map((item) => item === "other" ? (fields.otherDetails.trim() ? `Other: ${fields.otherDetails.trim()}` : "Other") : item); const response = await fetch("/api/submissions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...fields, interests: submittedInterests }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Something went wrong."); setStatus("success"); } catch (error) { setMessage(error instanceof Error ? error.message : "Please try again."); setStatus("error"); } }
  if (status === "success") return <div className="success"><div className="success-mark"><Check size={25} /></div><h2>Message received.</h2><p>Thank you for reaching out. A member of the EgyMedya team will be in touch shortly.</p><button className="button ghost" onClick={() => { setFields(initial); setStatus("idle"); }}>Send another</button></div>;
  const option = (value: Interest, label: React.ReactNode) => <label className="interest-check" key={value}><input type="checkbox" checked={fields.interests.includes(value)} onChange={() => toggleInterest(value)} /><span>{label}</span></label>;
  return <form onSubmit={submit} noValidate><div className="field"><label htmlFor="name">Full name</label><input id="name" value={fields.name} onChange={(e) => update("name", e.target.value)} placeholder="Your name" aria-invalid={!!errors.name} />{errors.name && <span className="error">{errors.name}</span>}</div><div className="field"><label htmlFor="phone">Phone number</label><input id="phone" value={fields.phone} onChange={(e) => update("phone", e.target.value)} placeholder="+1 (555) 000-0000" aria-invalid={!!errors.phone} />{errors.phone && <span className="error">{errors.phone}</span>}</div><div className="field"><label htmlFor="instagram">Instagram username <span className="optional">Optional</span></label><input id="instagram" value={fields.instagram} onChange={(e) => update("instagram", e.target.value)} placeholder="@yourhandle" aria-invalid={!!errors.instagram} />{errors.instagram && <span className="error">{errors.instagram}</span>}</div><div className="field"><label htmlFor="linkedin">LinkedIn profile <span className="optional">Optional</span></label><input id="linkedin" type="url" value={fields.linkedin} onChange={(e) => update("linkedin", e.target.value)} placeholder="https://linkedin.com/in/yourname" aria-invalid={!!errors.linkedin} />{errors.linkedin && <span className="error">{errors.linkedin}</span>}</div><div className="field"><label htmlFor="email">Email address</label><input id="email" type="email" value={fields.email} onChange={(e) => update("email", e.target.value)} placeholder="you@company.com" aria-invalid={!!errors.email} />{errors.email && <span className="error">{errors.email}</span>}</div><div className="interest-offer"><p>We help real estate professionals grow their brand through marketing, video content, and professional websites.</p><p className="interest-question">What are you most interested in? <span className="optional">Optional</span></p>{option("website", "Website")}{option("video", <span>Video Content (<strong>1st video free</strong>)</span>)}{option("marketing", "Marketing (Facebook & Instagram Ads)")}{option("other", "Other")}{fields.interests.includes("other") && <input type="text" className="other-input" placeholder="Please specify what you need..." value={fields.otherDetails} onChange={(e) => update("otherDetails", e.target.value)} maxLength={120} autoFocus />}</div><input tabIndex={-1} autoComplete="off" value={fields.website} onChange={(e) => update("website", e.target.value)} style={{ display: "none" }} aria-hidden="true" />{status === "error" && <span className="error">{message}</span>}<button className="button gold form-submit" disabled={status === "loading"}>{status === "loading" ? <><LoaderCircle size={16} /> Sending</> : <>Submit <ArrowUpRight size={17} /></>}</button><p className="privacy">Your information is kept private and used only to respond to your request.</p></form>;
}
