import { getSupabaseAdmin } from "@/lib/supabase/admin";
import { getSupabasePublic } from "@/lib/supabase/public";

export type Submission = { id: string; name: string; phone: string; instagram: string | null; linkedin: string | null; email: string; interestedInFreeVideo: boolean; createdAt: string };
type SubmissionRow = { id: string; name: string; phone: string; instagram: string | null; linkedin: string | null; email: string; interested_in_free_video: boolean; created_at: string };
function mapRow(row: SubmissionRow): Submission { return { id: row.id, name: row.name, phone: row.phone, instagram: row.instagram, linkedin: row.linkedin, email: row.email, interestedInFreeVideo: row.interested_in_free_video, createdAt: row.created_at }; }

export async function createSubmission(input: { name: string; phone: string; instagram: string | null; linkedin: string | null; email: string; interestedInFreeVideo: boolean }) { const { name, phone, instagram, linkedin, email, interestedInFreeVideo } = input; const { error } = await getSupabasePublic().from("submissions").insert({ name, phone, instagram, linkedin, email, interested_in_free_video: interestedInFreeVideo }); if (error) throw error; return "accepted"; }
export async function findRecentDuplicate(email: string, phone: string) { const since = new Date(Date.now() - 86_400_000).toISOString(); const { data, error } = await getSupabaseAdmin().from("submissions").select("id").or(`email.eq.${email},phone.eq.${phone}`).gte("created_at", since).limit(1); if (error) throw error; return data.length > 0; }
export async function listSubmissions(search: string, page: number, limit: number) { const from = (page - 1) * limit; const to = from + limit - 1; let query = getSupabaseAdmin().from("submissions").select("id,name,phone,instagram,linkedin,email,interested_in_free_video,created_at", { count: "exact" }).order("created_at", { ascending: false }).range(from, to); if (search) query = query.or(`name.ilike.%${search}%,email.ilike.%${search}%,phone.ilike.%${search}%,instagram.ilike.%${search}%,linkedin.ilike.%${search}%`); const { data, count, error } = await query; if (error) throw error; return { items: (data as SubmissionRow[]).map(mapRow), total: count ?? 0 }; }
export async function deleteSubmission(id: string) { const { error } = await getSupabaseAdmin().from("submissions").delete().eq("id", id); if (error) throw error; }
export async function updateSubmission(id: string, input: { name: string; phone: string; instagram: string | null; linkedin: string | null; email: string; interestedInFreeVideo: boolean }) { const { data, error } = await getSupabaseAdmin().from("submissions").update({ name: input.name, phone: input.phone, instagram: input.instagram, linkedin: input.linkedin, email: input.email, interested_in_free_video: input.interestedInFreeVideo }).eq("id", id).select("id,name,phone,instagram,linkedin,email,interested_in_free_video,created_at").single(); if (error) throw error; return mapRow(data as SubmissionRow); }
export async function deleteAllSubmissions() { const { error } = await getSupabaseAdmin().from("submissions").delete().not("id", "is", null); if (error) throw error; }
export async function countSubmissions(since?: string) { let query = getSupabaseAdmin().from("submissions").select("id", { count: "exact", head: true }); if (since) query = query.gte("created_at", since); const { count, error } = await query; if (error) throw error; return count ?? 0; }
export async function getExportRows() { const { data, error } = await getSupabaseAdmin().from("submissions").select("id,name,phone,instagram,linkedin,email,interested_in_free_video,created_at").order("created_at", { ascending: false }); if (error) throw error; return (data as SubmissionRow[]).map(mapRow); }